# Name : Rubaiyat Karim
ID: 2215151022
Section : 7A1

Tasks:



*   Run the code twice
*   With a fixed seed (np.random.seed(10)) to ensure reproducibility.
*   Without setting a seed, allowing random values to change each time.
*   Observe and explain the differences in outputs.





In [1]:
import numpy as np

In [2]:
np.random.seed(10)
matrix_with_seed = np.random.randint(1, 51, (3, 3))
print("Matrix with fixed seed:")
print(matrix_with_seed)

matrix_without_seed = np.random.randint(1, 51, (3, 3))
print("\nMatrix without fixed seed:")
print(matrix_without_seed)

Matrix with fixed seed:
[[10 37 16]
 [ 1 50 29]
 [26 30 49]]

Matrix without fixed seed:
[[30 50  9]
 [10  1 43]
 [41 37 17]]


*   With a Fixed Seed : Setting a fixed seed ensures that the random numbers remain identical every time the code is executed. This is useful when running the code multiple times but needing the matrix to stay the same.

*   Without a Seed : If no seed is set, the code will generate a different matrix with new random values each time it runs.

